import * as THREE from 'three';
export function windAt(time,x=0,z=0){const slow=.5+.5*Math.sin(time*.19+x*.024-z*.017);const gust=Math.pow(Math.max(0,Math.sin(time*.38-x*.032-z*.041)),3);return .10+.32*slow+.55*gust;}
export function createForestMotion(renderer){
 const u={windTime:{value:0},windAmount:{value:1}};let enabled=true,lastShadow=0,count=0;
 function patch(m,grass){const code=`vec4 wLocal=vec4(transformed,1.);\n#ifdef USE_INSTANCING\nwLocal=instanceMatrix*wLocal;\n#endif\nvec3 wp=(modelMatrix*wLocal).xyz;float sw=.5+.5*sin(windTime*.19+wp.x*.024-wp.z*.017);float gs=pow(max(0.,sin(windTime*.38-wp.x*.032-wp.z*.041)),3.);float breeze=.10+.32*sw+.55*gs;float weight=${grass?'clamp(transformed.y/.6,0.,1.)':'pow(clamp(transformed.y/15.,0.,1.),1.4)'};float disp=sin(windTime*${grass?'1.3':'.8'}+wp.x*.17+wp.z*.23)*breeze*windAmount*weight;transformed.x+=disp*${grass?'.07':'.13'};transformed.z+=disp*${grass?'.028':'.052'};`;
 m.onBeforeCompile=s=>{Object.assign(s.uniforms,u);s.vertexShader='uniform float windTime;uniform float windAmount;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\n'+code);};m.customProgramCacheKey=()=> 'v42-living-wind-'+grass;m.needsUpdate=true;}
 const depth=[false,true].map(g=>{let m=new THREE.MeshDepthMaterial({depthPacking:THREE.RGBADepthPacking});patch(m,g);return m;});
 return {registerModel(root){count=0;root.traverse(o=>{if(!o.isMesh)return;let mats=Array.isArray(o.material)?o.material:[o.material];if(mats.some(m=>/V32_针叶_|V32_树干|V32_根部|V42_林草_|V42_蕨叶_/.test(m.name))){const grass=mats.some(m=>/V42_林草_|V42_蕨叶_/.test(m.name));mats.forEach(m=>{m.side=THREE.DoubleSide;patch(m,grass)});o.customDepthMaterial=depth[grass?1:0];count++;}});},setEnabled(v){enabled=v;u.windAmount.value=v?1:0;renderer.shadowMap.needsUpdate=true;},update(t){if(enabled){u.windTime.value=t;if(t-lastShadow>1){lastShadow=t;renderer.shadowMap.needsUpdate=true;}}},debug(){return{enabled,time:u.windTime.value,patches:count,gust:enabled?windAt(u.windTime.value):0,canopyAmplitudeMax:.13,grassAmplitudeMax:.07};}};
}
